### ISSUE TITLE
Bug with let/var and for loop when transpile to ES2015 code 

### ISSUE THREAD

**Issue by gangstara2** [babel/minify#696] opened 2017-09-24 15:26 UTC
#### Input Code

```js
let abc = '123'
for (let i = 0; i < [1,2,3].length; i++) {
	abc = abc + '345'	
}

console.log(abc)
```

#### Actual Output

```js
'use strict';for(var i=0;i<[1,2,3].length;i++){}console.log(abc);
```

#### Expected Output

```js
for(var abc="123",i=0;i<[1,2,3].length;i++)abc+="345";console.log(abc);
```

#### Details

When I declare a let/var or even const variable before a for loop, It disappeared and make this variable undefined. You can test it with [Babel Repl](http://babeljs.io/repl/#?babili=true&browsers=&build=&builtIns=false&code_lz=MYewdgzgLgBAhgI2DAvDA5ARgEwGZ0BQAZiAE4wAUANgKawCWqMADANwyMA8MA2pgDTZ-uALoA6WmADmUABbt6AakUBKGAG8CBAL5bQkELQkgpFRMBVA&debug=false&circleciRepo=&evaluate=false&lineWrap=false&presets=es2015%2Cbabili&prettier=false&targets=&version=6.26.0)

**Comment by boopathi** [comment] 2017-09-25 12:07
Closing this as duplicate of #485

**Closed by boopathi** 2017-09-25 12:07 UTC
Labels: bug, with es2015
