### ISSUE TITLE
change statements  scope

### ISSUE THREAD

**Issue by LiJohnson** [babel/minify#697] opened 2017-09-25 12:22 UTC
#### Input Code

```js
var a = 0;
for( var b = a; b < 10;b++ );
for( var c = a; c < 10;c++ );
```

#### Actual Output

```js
for(var a=0,b=a;10>b;b++);for(var c=a;10>c;c++);
```

#### Expected Output

```js
var a=0;for(var b=a;10>b;b++);for(var c=a;10>c;c++);
```

#### Details
It has changed the statement `a` scope; while `for(var c=a;10>c;c++);`throws an undefined error

**Comment by nicolo-ribaudo** [comment] 2017-09-25 12:51
`a` is not undefined there:

```js
for(var a=0,b=a;10>b;b++);for(var c=(console.log(a),a);10>c;c++);
```
Logs `0`.

**Comment by boopathi** [comment] 2017-09-25 12:56
`var`s are hoisted. This doesn’t throw any error. If it throws in a browser, then it’s a browser bug. In which browser are you seeing this?

Going to close this as this transformation is intentional and not a bug. Please comment to reopen if there is a bug.

**Closed by boopathi** 2017-09-25 12:56 UTC

**Comment by LiJohnson** [comment] 2017-09-29 05:15
that is correct!
but in fact my input code is
```JS
let a = 0;
for( let b = a; b < 10;b++ );
for( let c = a; c < 10;c++ );
```
I am using `let`;
output code is 
```js
"use strict";for(var b=0;10>b;b++);for(var c=a;10>c;c++);
```
`a`  will throw an undefined error
