### ISSUE TITLE
these code crashes node

### ISSUE THREAD

**Issue by xxoo** [babel/minify#909] opened 2018-09-27 15:31 UTC
**To Reproduce**

Minimal code to reproduce the bug

```js
var babel = require('@babel/core');
var minify = require('babel-preset-minify');
babel.transformFileSync('kernel.js', {
	presets: [minify],
	babelrc: false
});
babel.transformFileSync('touchguesture.js', {
	presets: [minify],
	babelrc: false
});
```
[Archive.zip](https://github.com/babel/minify/files/2424712/Archive.zip) contains kernel.js and touchguesture.js

**Actual Output**

```
/Volumes/data/lib/node_modules/siteBuild/node_modules/babel-plugin-minify-builtins/lib/index.js:191
            throw _iteratorError;
            ^

Error: Couldn't find intersection
    at NodePath.getDeepestCommonAncestorFrom (/Volumes/data/lib/node_modules/siteBuild/node_modules/@babel/traverse/lib/path/ancestry.js:153:11)
    at getSegmentedSubPaths (/Volumes/data/lib/node_modules/siteBuild/node_modules/babel-plugin-minify-builtins/lib/index.js:244:14)
    at BuiltInReplacer.replace (/Volumes/data/lib/node_modules/siteBuild/node_modules/babel-plugin-minify-builtins/lib/index.js:92:31)
    at PluginPass.exit (/Volumes/data/lib/node_modules/siteBuild/node_modules/babel-plugin-minify-builtins/lib/index.js:205:27)
    at newFn (/Volumes/data/lib/node_modules/siteBuild/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/Volumes/data/lib/node_modules/siteBuild/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Volumes/data/lib/node_modules/siteBuild/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Volumes/data/lib/node_modules/siteBuild/node_modules/@babel/traverse/lib/path/context.js:97:8)
    at TraversalContext.visitQueue (/Volumes/data/lib/node_modules/siteBuild/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/Volumes/data/lib/node_modules/siteBuild/node_modules/@babel/traverse/lib/context.js:90:19)
```

**Configuration**

nodejs version: `10.11.0`

babel-minify version: `0.5.0`

babel version : `7.1.0`

**Comment by vigneshshanmugam** [comment] 2018-09-27 21:46
duplicate of #904 , Thanks for the test files though.

**Closed by vigneshshanmugam** 2018-09-27 21:46 UTC
