### ISSUE TITLE
Minify preset fails but not minify-cli

### ISSUE THREAD

**Issue by clemstoquart** [babel/minify#707] opened 2017-10-10 22:49 UTC
Hello,

#### Input Code

```js
function showBug() {
	let myVar = '';
	for (let i = 0; i < 2; i++) {
		myVar += 'A';
	}
	return myVar;
}
```
That code works as expected.

#### Actual Output

```js
function showBug() {
	for(var a=0;2>a;a++) {
		
	}
	return myVar
}

/*
Exception: ReferenceError: myVar is not defined
*/
```
The babellify + minify code doesn't work :(

#### Expected Output

```js
function showBug(){
	for(var a='',b=0;2>b;b++)
		a+='A';
	return a
}
```
#### .babelrc
```js
{
  "presets": [
    ["env", {
      "targets": {
        "ie": 11
      }
    }], "minify"
  ]
}
```

#### Details
Where it becomes interesting is that when I run both babel and minify separately (using cli) one after another the output is the expected one !

#### Environment
Node.js : 8.6
Npm : 5.3
babel-cli : 6.26.0
babel-preset-minify : 0.2.0

I hope I gave enough information :)

**Comment by boopathi** [comment] 2017-10-25 22:16
Marking as duplicate of #594

**Closed by boopathi** 2017-10-25 22:16 UTC
Labels: duplicate
