### ISSUE TITLE
[bug] Error: Reading input from STDIN. Cannot take file params 

### ISSUE THREAD

**Issue by HaoZeke** [babel/minify#719] opened 2017-11-09 22:03 UTC
Running  

```bash
minify src/js/sideNav.js --mangle.keepClassName --deadcode.keepFnArgs --outFile main.js.min
```
From the terminal works fine...

However when I run it through [tup](http://gittup.org/tup) I get,

```bash
Error: Reading input from STDIN. Cannot take file params   
```

I have it installed with 

```bash
yarn global add babel-minify
```

**Comment by boopathi** [comment] 2017-11-10 09:41
I've not used tup. Maybe you can help debug what happens in tup and apply a fix that works everywhere. PR welcome. Thanks.

This is how we decide which input form to take - https://github.com/babel/minify/blob/9d4fbfa52988c47f1482bee2c87a603598622c1c/packages/babel-minify/src/cli.js#L258-L268

**Comment by xeho91** [comment] 2017-11-13 14:55
I'm receiving same error message when I am trying to use it with [nodemon ](https://www.npmjs.com/package/nodemon).

In my npm scripts, I've got this command:`"babel:min": "nodemon --watch library --exec \"minify library -d bin\""`

In terminal I get following:
```
❯ npm run babel:min

> ******@0.1.0 babel:min C:\Users\xeho91\**\**
> nodemon --watch library --exec "minify library -d bin"

[nodemon] 1.12.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: C:\Users\xeho91\GitHub\boilerplate\library/**/*
[nodemon] starting `minify library/boilerplate.js -d bin/boilerplate.js`
Error: Reading input from STDIN. Cannot take file params
[nodemon] app crashed - waiting for file changes before starting...
```

Depedencies:
    "@babel/cli": "^7.0.0-beta.31",
    "@babel/core": "^7.0.0-beta.31",
    "@babel/node": "^7.0.0-beta.31",
    "@babel/polyfill": "^7.0.0-beta.31",
    "@babel/preset-env": "^7.0.0-beta.31",
    "babel-eslint": "^8.0.2",
    "babel-minify": "^0.2.0",
    "nodemon": "^1.12.1",

System: Windows 10 x64
NodeJS: v8.9.1 LTS
npm: v.5.5.1

**Comment by curiousdannii** [comment] 2017-11-29 01:43
I'm having the same error when running through make.

```
babel-minify dist/$*.js >> $@
```

**Comment by marcofugaro** [comment] 2017-12-02 00:53
Happens to me also when I run `yarn test`. Here are the relevant scripts
```js
  "build": "rollup -c && npm run minify",
  "minify": "minify build/get-package-github-url.js --out-file build/get-package-github-url.min.js",
  "pretest": "npm run build",
  "test": "ava",
```

**Comment by boopathi** [comment] 2017-12-22 16:52
I'm not able to reproduce this by calling `minify` from a makefile or package.json script or nodemon's exec script. Can someone help create a repo that reproduces this issue ?

**Comment by curiousdannii** [comment] 2017-12-29 12:02
Works for me now, maybe a dependency was fixed?

**Comment by evenfrost** [comment] 2018-01-08 12:08
Same for me when using inside Docker (e.g. with `docker build`).
`Dockerfile`:
```dockerfile
RUN npm run compress:scripts
```
`package.json`'s scripts:
```js
"compress:scripts": "minify ./public/scripts.js -d ./public"
```
Output:
```bash
Error: Reading input from STDIN. Cannot take file params
```

A possible workaround, since `minify` is outputting to STDIN by default, and if you're using no arguments but `-d` is to use following notation:
```bash
minify < ./public/scripts.js > ./public/scripts.js
```

**Comment by curiousdannii** [comment] 2018-01-21 11:51
@boopathi I've just rerun it on Travis (so it's downloading the latest compatible packages) and the error still occurs.

**Comment by curiousdannii** [comment] 2018-03-29 04:52
Is there any way to move this forward? Can I provide any extra information?

**Comment by boopathi** [comment] 2018-04-08 08:35
I'm closing this. Please comment to reopen this.

**Closed by boopathi** 2018-04-08 08:35 UTC
Labels: bug, help wanted, needs info
