### ISSUE TITLE
Minifying breaks adding to a variable in a loop

### ISSUE THREAD

**Issue by clayne11** [babel/minify#702] opened 2017-10-02 17:25 UTC
The variable being added in the loop isn't even declared.

#### Input Code

```js
export default function addLoop() {
  let retVal = ''
  for (let index = 0; index < 20; index++) {
    retVal += 'a'
  }
  return retVal
}
```

#### Actual Output

```js
'use strict';Object.defineProperty(exports,'__esModule',{value:!0}),exports.default=addLoop;function addLoop(){for(var b=0;20>b;b++){}return a}
```

#### Expected Output

```js
'use strict';Object.defineProperty(exports,'__esModule',{value:!0}),exports.default=addLoop;function addLoop(){var a='';for(var b=0;20>b;b++){a+='a'}return a}
```

**Comment by boopathi** [comment] 2017-10-03 20:15
Are you using alongside env preset or es2015 preset ?

**Comment by boopathi** [comment] 2017-10-03 20:31
Duplicate of #594

**Comment by clayne11** [comment] 2017-10-03 20:31
I am using the `es2015` preset.

**Closed by boopathi** 2017-10-03 20:31 UTC
Labels: bug

**Comment by mattleong** [comment] 2017-10-04 21:02
@clayne11 Any luck figuring it out? I'm running into the same issue.
